name: yolov8_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - lap
  - filterpy
  - opencv
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
    - ultralytics
    - sort
    - hikvisionapi
    - logging

