name: yolo_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - lap
  - filterpy
  - opencv
  - matplotlib
  - pytorch=2.0
  - torchvision=0.15
  - torchaudio=2.0
  - cpuonly
  - libjpeg-turbo
  - libpng
  - pip
  - pip:
    - ultralytics
    - hikvisionapi
    - python-dotenv
    - google-auth
    - google-auth-oauthlib
    - google-auth-httplib2
    - google-api-python-client
    - openpyxl
    - xlsxwriter
  